backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: 'Level 1'
    name: 'level_1'
    format: 'json'
    files:
      - label: 'Content'
        name: 'content'
        file: 'assets/content/levels/level_1.json'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string }

  - name: 'about'
    label: 'A propos'
    format: 'json'
    extension: 'json'
    folder: 'assets/content/about'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
