backend:
  name: git-gateway
  branch: develop

media_folder: static/img
public_folder: /img

collections:
  - label: 'Stage 1'
    name: 'level1'
    format: 'json'
    files:
      - label: 'Content'
        name: 'content'
        file: 'assets/content/levels/level1.json'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Nickname, name: nickname, widget: string }
  - label: 'Stage 2'
    name: 'level2'
    format: 'json'
    files:
      - label: 'Content'
        name: 'content'
        file: 'assets/content/levels/level2.json'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Nickname, name: nickname, widget: string }

  - name: 'about'
    label: 'A propos'
    format: 'json'
    extension: 'json'
    folder: 'assets/content/about'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }

  - name: 'posts'
    label: 'Posts'
    format: 'json'
    extension: 'json'
    folder: 'assets/content/posts'
    create: true
    slug: '{{day}}-{{hour}}-{{minute}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'picture', widget: 'image', required: false }
      - {
          label: 'Réseaux social',
          name: 'social_network',
          widget: 'select',
          options: ['Facebook', 'Twitter', 'Instagram', 'Snapchat'],
        }

  - label: 'Solutions'
    name: 'solutions'
    format: 'json'
    folder: 'assets/content/solutions'
    create: true
    slug: '{{day}}-{{hour}}-{{minute}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'ID', name: 'id', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Required score',
          name: 'required_score',
          widget: 'number',
          valueType: 'int',
          min: 0,
        }
      - {
          label: 'Stage',
          name: 'stage',
          widget: 'number',
          valueType: 'int',
          min: 0,
        }
      - { label: 'Content', name: 'content', widget: 'markdown' }
