backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'Levels'
    label: 'Levels'
    format: 'json'
    folder: 'assets/content/levels'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Relation',
          name: 'Relation',
          widget: 'relation',
          collection: 'level_1',
          valueField: 'name.first',
        }
  - name: 'level_1'
    label: 'Level 1'
    format: 'json'
    folder: 'assets/content/level1'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
